services:
  - type: worker
    name: gold-price-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
